console.log("This is generated by main.js")

const btn1 = document.getElementById("btn1")
const btn2 = document.getElementById("btn2")
const btn2_animate = document.getElementsByClassName("btn2")
const slider2 = document.querySelector(".slider_2")
const slider = document.querySelector(".slider")

const t1 = gsap.timeline();

btn1.addEventListener("click", (e) => {
    t1.fromTo(slider,{opacity: 0}, {opacity: 1})
    .fromTo(slider2,{x: "100%"},{duration: 1, x: "0", ease: "power4.in"})
    .fromTo(btn2_animate,{y: "30px"},{y: "0", ease: "power4.in"})
    slider.classList.add("pointer");
})

btn2.addEventListener("click", (e) => {
    t1.fromTo(slider2,{x: "0"},{duration: 1, x: "100%", ease: "power4.out"})
    .fromTo(slider,{opacity: 1}, {opacity: 0})
    slider.classList.remove("pointer")
})