console.log("This is generated by main.js")

const btn1 = document.getElementById('btn1')



btn1.addEventListener('click', (e) => {
    anime({
        targets: '.morph',
        d: [
        { value: 'M0,0h1080v1151.6c0,0-240.6-852.2-540-1151.6S0-175.9,0,23.9V0z'},
        { value: 'M0,0h1080v1151.6c0,0-240.6,284.1-540-15.3S0-175.9,0,23.9V0z'},
        { value: 'M0,0h1080v1151.6c0,0-240.6,284.1-540-15.3S0,1073.6,0,1273.5V0z'},
        { value: 'M0,0h1080v1920c0,0-240.6-484.3-540-783.7S0,1073.6,0,1273.5V0z'},
        { value: 'M0,0h1080v1920c0,0-240.6-484.3-540-783.7S0,1720.1,0,1920V0z',},
        { value: 'M0,0h1080v1920c0,0-240.6,299.4-540,0S0,1720.1,0,1920V0z'},
        ],
        easing: 'easeOutQuad',
        duration: 3000,
        loop: false
    });
})