console.log("This is generated by main.js")

const btn1 = document.getElementById('btn1')



btn1.addEventListener('click', (e) => {
    anime({
        targets: '.morph',
        d: [
        { value: 'M0,0h1080v960C1080,960,0,1115.3,0,0z'},
        { value: 'M0,0h1080v1920C1080,1920,0,1115.3,0,0z'},
        ],
        easing: 'easeOutQuad',
        duration: 1500,
        loop: false
    });
})